export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const CLEAR_LOGIN_SUCCESS = "CLEAR_ERRORS";

export const LOAD_RECORD_REQUEST = "LOAD_RECORD_REQUEST";
export const LOAD_RECORD_SUCCESS = "LOAD_RECORD_SUCCESS";
export const LOAD_RECORD_FAIL = "LOAD_RECORD_FAIL";
export const CLEAR_GET_ALL_URL_STREAMER_FAIL =
  "CLEAR_GET_ALL_URL_STREAMER_FAIL";
